INSERT INTO paises (nome_pais) VALUES ("Afghanistan");
INSERT INTO paises (nome_pais) VALUES ("Albania");
INSERT INTO paises (nome_pais) VALUES ("Algeria");
INSERT INTO paises (nome_pais) VALUES ("American Samoa");
INSERT INTO paises (nome_pais) VALUES ("Andorra");
INSERT INTO paises (nome_pais) VALUES ("Angola");
INSERT INTO paises (nome_pais) VALUES ("Anguilla");
INSERT INTO paises (nome_pais) VALUES ("Antarctica");
INSERT INTO paises (nome_pais) VALUES ("Antigua and Barbuda");
INSERT INTO paises (nome_pais) VALUES ("Argentina");
INSERT INTO paises (nome_pais) VALUES ("Armenia");
INSERT INTO paises (nome_pais) VALUES ("Aruba");
INSERT INTO paises (nome_pais) VALUES ("Australia");
INSERT INTO paises (nome_pais) VALUES ("Austria");
INSERT INTO paises (nome_pais) VALUES ("Azerbaijan");
INSERT INTO paises (nome_pais) VALUES ("Bahamas");
INSERT INTO paises (nome_pais) VALUES ("Bahrain");
INSERT INTO paises (nome_pais) VALUES ("Bangladesh");
INSERT INTO paises (nome_pais) VALUES ("Barbados");
INSERT INTO paises (nome_pais) VALUES ("Belarus");
INSERT INTO paises (nome_pais) VALUES ("Belgium");
INSERT INTO paises (nome_pais) VALUES ("Belize");
INSERT INTO paises (nome_pais) VALUES ("Benin");
INSERT INTO paises (nome_pais) VALUES ("Bermuda");
INSERT INTO paises (nome_pais) VALUES ("Bhutan");
INSERT INTO paises (nome_pais) VALUES ("Bolivia");
INSERT INTO paises (nome_pais) VALUES ("Bosnia and Herzegovina");
INSERT INTO paises (nome_pais) VALUES ("Botswana");
INSERT INTO paises (nome_pais) VALUES ("Bouvet Island");
INSERT INTO paises (nome_pais) VALUES ("Brazil");
INSERT INTO paises (nome_pais) VALUES ("British Indian Ocean Territory");
INSERT INTO paises (nome_pais) VALUES ("Brunei Darussalam");
INSERT INTO paises (nome_pais) VALUES ("Bulgaria");
INSERT INTO paises (nome_pais) VALUES ("Burkina");
INSERT INTO paises (nome_pais) VALUES ("Burundi");
INSERT INTO paises (nome_pais) VALUES ("Cambodia");
INSERT INTO paises (nome_pais) VALUES ("Cameroon");
INSERT INTO paises (nome_pais) VALUES ("Canada");
INSERT INTO paises (nome_pais) VALUES ("Cape Verde");
INSERT INTO paises (nome_pais) VALUES ("Cayman Islands");
INSERT INTO paises (nome_pais) VALUES ("Central African Republic");
INSERT INTO paises (nome_pais) VALUES ("Chad");
INSERT INTO paises (nome_pais) VALUES ("Chile");
INSERT INTO paises (nome_pais) VALUES ("China");
INSERT INTO paises (nome_pais) VALUES ("Christmas Island");
INSERT INTO paises (nome_pais) VALUES ("Cocos (Keeling) Islands");
INSERT INTO paises (nome_pais) VALUES ("Colombia");
INSERT INTO paises (nome_pais) VALUES ("Comoros");
INSERT INTO paises (nome_pais) VALUES ("Congo");
INSERT INTO paises (nome_pais) VALUES ("Cook Islands");
INSERT INTO paises (nome_pais) VALUES ("Costa Rica");
INSERT INTO paises (nome_pais) VALUES ("Cote D'ivoire");
INSERT INTO paises (nome_pais) VALUES ("Croatia");
INSERT INTO paises (nome_pais) VALUES ("Cuba");
INSERT INTO paises (nome_pais) VALUES ("Cyprus");
INSERT INTO paises (nome_pais) VALUES ("Czech Republic");
INSERT INTO paises (nome_pais) VALUES ("Denmark");
INSERT INTO paises (nome_pais) VALUES ("Djibouti");
INSERT INTO paises (nome_pais) VALUES ("Dominica");
INSERT INTO paises (nome_pais) VALUES ("Dominican Republic");
INSERT INTO paises (nome_pais) VALUES ("Ecuador");
INSERT INTO paises (nome_pais) VALUES ("Egypt");
INSERT INTO paises (nome_pais) VALUES ("El Salvador");
INSERT INTO paises (nome_pais) VALUES ("Equatorial Guinea");
INSERT INTO paises (nome_pais) VALUES ("Eritrea");
INSERT INTO paises (nome_pais) VALUES ("Estonia");
INSERT INTO paises (nome_pais) VALUES ("Ethiopia");
INSERT INTO paises (nome_pais) VALUES ("Falkland Islands");
INSERT INTO paises (nome_pais) VALUES ("FaroeIslands");
INSERT INTO paises (nome_pais) VALUES ("Fiji");
INSERT INTO paises (nome_pais) VALUES ("Finland");
INSERT INTO paises (nome_pais) VALUES ("France");
INSERT INTO paises (nome_pais) VALUES ("French Guiana");
INSERT INTO paises (nome_pais) VALUES ("French Polynesia");
INSERT INTO paises (nome_pais) VALUES ("French Southern Territories");
INSERT INTO paises (nome_pais) VALUES ("Gabon");
INSERT INTO paises (nome_pais) VALUES ("Gambia");
INSERT INTO paises (nome_pais) VALUES ("Georgia");
INSERT INTO paises (nome_pais) VALUES ("Germany");
INSERT INTO paises (nome_pais) VALUES ("Ghana");
INSERT INTO paises (nome_pais) VALUES ("Gibraltar");
INSERT INTO paises (nome_pais) VALUES ("Greece");
INSERT INTO paises (nome_pais) VALUES ("Greenland");
INSERT INTO paises (nome_pais) VALUES ("Grenada");
INSERT INTO paises (nome_pais) VALUES ("Guadeloupe");
INSERT INTO paises (nome_pais) VALUES ("Guam");
INSERT INTO paises (nome_pais) VALUES ("Guatemala");
INSERT INTO paises (nome_pais) VALUES ("Guinea");
INSERT INTO paises (nome_pais) VALUES ("Guinea-bissau");
INSERT INTO paises (nome_pais) VALUES ("Guyana");
INSERT INTO paises (nome_pais) VALUES ("Haiti");
INSERT INTO paises (nome_pais) VALUES ("Heard Island");
INSERT INTO paises (nome_pais) VALUES ("Honduras");
INSERT INTO paises (nome_pais) VALUES ("Hong Kong");
INSERT INTO paises (nome_pais) VALUES ("Hungary");
INSERT INTO paises (nome_pais) VALUES ("Iceland");
INSERT INTO paises (nome_pais) VALUES ("India");
INSERT INTO paises (nome_pais) VALUES ("Indonesia");
INSERT INTO paises (nome_pais) VALUES ("Iran, Islamic Republic");
INSERT INTO paises (nome_pais) VALUES ("Iraq");
INSERT INTO paises (nome_pais) VALUES ("Ireland");
INSERT INTO paises (nome_pais) VALUES ("Israel");
INSERT INTO paises (nome_pais) VALUES ("Italy");
INSERT INTO paises (nome_pais) VALUES ("Jamaica");
INSERT INTO paises (nome_pais) VALUES ("Japan");
INSERT INTO paises (nome_pais) VALUES ("Jordan");
INSERT INTO paises (nome_pais) VALUES ("Kazakhstan");
INSERT INTO paises (nome_pais) VALUES ("Kenya");
INSERT INTO paises (nome_pais) VALUES ("Kiribati");
INSERT INTO paises (nome_pais) VALUES ("Kuwait");
INSERT INTO paises (nome_pais) VALUES ("Kyrgyzstan");
INSERT INTO paises (nome_pais) VALUES ("Lao");
INSERT INTO paises (nome_pais) VALUES ("Latvia");
INSERT INTO paises (nome_pais) VALUES ("Lebanon");
INSERT INTO paises (nome_pais) VALUES ("Lesotho");
INSERT INTO paises (nome_pais) VALUES ("Liberia");
INSERT INTO paises (nome_pais) VALUES ("Libyan Arab Jamahiriya");
INSERT INTO paises (nome_pais) VALUES ("Liechtenstein");
INSERT INTO paises (nome_pais) VALUES ("Lithuania");
INSERT INTO paises (nome_pais) VALUES ("Luxembourg");
INSERT INTO paises (nome_pais) VALUES ("Macao");
INSERT INTO paises (nome_pais) VALUES ("Macedonia");
INSERT INTO paises (nome_pais) VALUES ("Madagascar");
INSERT INTO paises (nome_pais) VALUES ("Malawi");
INSERT INTO paises (nome_pais) VALUES ("Malaysia");
INSERT INTO paises (nome_pais) VALUES ("Maldives");
INSERT INTO paises (nome_pais) VALUES ("Mali");
INSERT INTO paises (nome_pais) VALUES ("Malta");
INSERT INTO paises (nome_pais) VALUES ("Marshall Islands");
INSERT INTO paises (nome_pais) VALUES ("Martinique");
INSERT INTO paises (nome_pais) VALUES ("Mauritania");
INSERT INTO paises (nome_pais) VALUES ("Mauritius");
INSERT INTO paises (nome_pais) VALUES ("Mayotte");
INSERT INTO paises (nome_pais) VALUES ("Mexico");
INSERT INTO paises (nome_pais) VALUES ("Micronesia");
INSERT INTO paises (nome_pais) VALUES ("Moldova");
INSERT INTO paises (nome_pais) VALUES ("Monaco");
INSERT INTO paises (nome_pais) VALUES ("Mongolia");
INSERT INTO paises (nome_pais) VALUES ("Montserrat");
INSERT INTO paises (nome_pais) VALUES ("Morocco");
INSERT INTO paises (nome_pais) VALUES ("Mozambique");
INSERT INTO paises (nome_pais) VALUES ("Myanmar");
INSERT INTO paises (nome_pais) VALUES ("Namibia");
INSERT INTO paises (nome_pais) VALUES ("Nauru");
INSERT INTO paises (nome_pais) VALUES ("Nepal");
INSERT INTO paises (nome_pais) VALUES ("Netherlands");
INSERT INTO paises (nome_pais) VALUES ("Netherlands Antilles");
INSERT INTO paises (nome_pais) VALUES ("New Caledonia");
INSERT INTO paises (nome_pais) VALUES ("New Zealand");
INSERT INTO paises (nome_pais) VALUES ("Nicaragua");
INSERT INTO paises (nome_pais) VALUES ("Niger");
INSERT INTO paises (nome_pais) VALUES ("Nigeria");
INSERT INTO paises (nome_pais) VALUES ("Niue");
INSERT INTO paises (nome_pais) VALUES ("Norfolk Island");
INSERT INTO paises (nome_pais) VALUES ("North Korea");
INSERT INTO paises (nome_pais) VALUES ("Northern Mariana Islands");
INSERT INTO paises (nome_pais) VALUES ("Norway");
INSERT INTO paises (nome_pais) VALUES ("Oman");
INSERT INTO paises (nome_pais) VALUES ("Pakistan");
INSERT INTO paises (nome_pais) VALUES ("Palau");
INSERT INTO paises (nome_pais) VALUES ("Palestine");
INSERT INTO paises (nome_pais) VALUES ("Panama");
INSERT INTO paises (nome_pais) VALUES ("Papua New Guinea");
INSERT INTO paises (nome_pais) VALUES ("Paraguay");
INSERT INTO paises (nome_pais) VALUES ("Peru");
INSERT INTO paises (nome_pais) VALUES ("Philippines");
INSERT INTO paises (nome_pais) VALUES ("Pitcairn");
INSERT INTO paises (nome_pais) VALUES ("Poland");
INSERT INTO paises (nome_pais) VALUES ("Portugal");
INSERT INTO paises (nome_pais) VALUES ("Puerto Rico");
INSERT INTO paises (nome_pais) VALUES ("Qatar");
INSERT INTO paises (nome_pais) VALUES ("Reunion");
INSERT INTO paises (nome_pais) VALUES ("Romania");
INSERT INTO paises (nome_pais) VALUES ("Russian Federation");
INSERT INTO paises (nome_pais) VALUES ("Rwanda");
INSERT INTO paises (nome_pais) VALUES ("Saint Helena");
INSERT INTO paises (nome_pais) VALUES ("Saint Kitts and Nevis");
INSERT INTO paises (nome_pais) VALUES ("Saint Lucia");
INSERT INTO paises (nome_pais) VALUES ("Saint Pierre and Miquelon");
INSERT INTO paises (nome_pais) VALUES ("Saint Vincent");
INSERT INTO paises (nome_pais) VALUES ("Samoa");
INSERT INTO paises (nome_pais) VALUES ("San Marino");
INSERT INTO paises (nome_pais) VALUES ("Sao Tome and Principe");
INSERT INTO paises (nome_pais) VALUES ("Saudi Arabia");
INSERT INTO paises (nome_pais) VALUES ("Senegal");
INSERT INTO paises (nome_pais) VALUES ("Serbia and Montenegro");
INSERT INTO paises (nome_pais) VALUES ("Seychelles");
INSERT INTO paises (nome_pais) VALUES ("Sierra Leone");
INSERT INTO paises (nome_pais) VALUES ("Singapore");
INSERT INTO paises (nome_pais) VALUES ("Slovakia");
INSERT INTO paises (nome_pais) VALUES ("Slovenia");
INSERT INTO paises (nome_pais) VALUES ("Solomon Islands");
INSERT INTO paises (nome_pais) VALUES ("Somalia");
INSERT INTO paises (nome_pais) VALUES ("South Africa");
INSERT INTO paises (nome_pais) VALUES ("South Georgia");
INSERT INTO paises (nome_pais) VALUES ("South Korea");
INSERT INTO paises (nome_pais) VALUES ("Spain");
INSERT INTO paises (nome_pais) VALUES ("Sri Lanka");
INSERT INTO paises (nome_pais) VALUES ("Sudan");
INSERT INTO paises (nome_pais) VALUES ("Suriname");
INSERT INTO paises (nome_pais) VALUES ("Svalbard and Jan Mayen");
INSERT INTO paises (nome_pais) VALUES ("Swaziland");
INSERT INTO paises (nome_pais) VALUES ("Sweden");
INSERT INTO paises (nome_pais) VALUES ("Switzerland");
INSERT INTO paises (nome_pais) VALUES ("Syria");
INSERT INTO paises (nome_pais) VALUES ("Taiwan");
INSERT INTO paises (nome_pais) VALUES ("Tajikistan");
INSERT INTO paises (nome_pais) VALUES ("Tanzania");
INSERT INTO paises (nome_pais) VALUES ("Thailand");
INSERT INTO paises (nome_pais) VALUES ("Timor-leste");
INSERT INTO paises (nome_pais) VALUES ("Togo");
INSERT INTO paises (nome_pais) VALUES ("Tokelau");
INSERT INTO paises (nome_pais) VALUES ("Tonga");
INSERT INTO paises (nome_pais) VALUES ("Trinidad and Tobago");
INSERT INTO paises (nome_pais) VALUES ("Tunisia");
INSERT INTO paises (nome_pais) VALUES ("Turkey");
INSERT INTO paises (nome_pais) VALUES ("Turkmenistan");
INSERT INTO paises (nome_pais) VALUES ("Turks and Caicos Islands");
INSERT INTO paises (nome_pais) VALUES ("Tuvalu");
INSERT INTO paises (nome_pais) VALUES ("Uganda");
INSERT INTO paises (nome_pais) VALUES ("Ukraine");
INSERT INTO paises (nome_pais) VALUES ("United Arab Emirates");
INSERT INTO paises (nome_pais) VALUES ("United Kingdom");
INSERT INTO paises (nome_pais) VALUES ("United States");
INSERT INTO paises (nome_pais) VALUES ("Uruguay");
INSERT INTO paises (nome_pais) VALUES ("Uzbekistan");
INSERT INTO paises (nome_pais) VALUES ("Vanuatu");
INSERT INTO paises (nome_pais) VALUES ("Venezuela");
INSERT INTO paises (nome_pais) VALUES ("Viet Nam");
INSERT INTO paises (nome_pais) VALUES ("Virgin Islands, British");
INSERT INTO paises (nome_pais) VALUES ("Virgin Islands, U.S.");
INSERT INTO paises (nome_pais) VALUES ("Wallis and Futuna");
INSERT INTO paises (nome_pais) VALUES ("Western Sahara");
INSERT INTO paises (nome_pais) VALUES ("Yemen");
INSERT INTO paises (nome_pais) VALUES ("Zambia");
INSERT INTO paises (nome_pais) VALUES ("Zimbabwe");